### ISSUE TITLE
Which version of `huggingface_hub` to use

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/transformers-bloom-inference#15]
Hi there!

Thanks for the amazing inference scripts 🔥 
I am trying to run it in an offline mode, with the latest version of `huggingface_hub`. I am getting this issue while running the command:

``
TRANSFORMERS_OFFLINE=1,HF_HUB_OFFLINE=1 deepspeed --num_gpus 8 bloom-inference-scripts/bloom-ds-inference.py --name /gpfsscratch/rech/six/uan68tv/distill-bloom/models/bloom/
``

Error below:
 
```
    return f(*args, **kwargs)
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 92, in _inner_fn
Traceback (most recent call last):
  File "/gpfsssd/scratch/rech/six/uan68tv/distill-bloom/code/transformers-bloom-inference/bloom-inference-scripts/bloom-ds-inference.py", line 184, in <module>
    validate_repo_id(arg_value)
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 136, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/gpfsscratch/rech/six/uan68tv/distill-bloom/models/bloom/'. Use `repo_type` argument if needed.
    repo_root = get_repo_root(model_name)
  File "/gpfsssd/scratch/rech/six/uan68tv/distill-bloom/code/transformers-bloom-inference/bloom-inference-scripts/bloom-ds-inference.py", line 80, in get_repo_root
    cached_repo_dir = snapshot_download(
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 98, in inner_f
    return f(*args, **kwargs)
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 92, in _inner_fn
    validate_repo_id(arg_value)
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 136, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/gpfsscratch/rech/six/uan68tv/distill-bloom/models/bloom/'. Use `repo_type` argument if needed.
```

It's probably related to the `huggingface_hub` version but also I suspect that I might be doing something wrong. I naively copied the full copy of the HF bloom repo to `/gpfsscratch/rech/six/uan68tv/distill-bloom/models/bloom/`

Thanks !

**Comment by mayank31398** [comment]
Hi @younesbelkada , I have been using 0.9.1

**Comment by younesbelkada** [comment]
Thanks a lot! After updating it with the correct version I am getting:
```
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
        conn = connection.create_connection(conn = connection.create_connection(

    conn = connection.create_connection(      File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
conn = connection.create_connection(  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection

conn = connection.create_connection(

  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
conn = connection.create_connection(  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection

  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    conn = connection.create_connection(
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/gpfswork/rech/six/commun/conda/younes-distill-bert/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
```

I will try to upgrade the transformers version and see if it helps

**Comment by mayank31398** [comment]
I think you can't use snapshot_download in offline mode? I am not sure.
It checks for changes in the model bucket on HF hub.

**Comment by mayank31398** [comment]
I think I see the problem @younesbelkada 
https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-inference.py#L80-L82 tries downloading the model which doesn't exist.
`/gpfsscratch/rech/six/uan68tv/distill-bloom/models/bloom/` is not a bucket on HF-hub.
Can you try replacing snapshot_download?

**Comment by younesbelkada** [comment]
Great catch! It seems to work like charm now while forcing ` cached_repo_dir = model_name_or_path` - However, I think that I never entered inside the `is_offline_mode()` condition even by running the script with `TRANSFORMERS_OFFLINE=1` prepended, maybe there is something wrong with this function 🤔 
Also with the forcing strategy I have to re-create the DS-checkpoints at each run since the function does not try to load the DS-checkpoints from the cache

**Comment by younesbelkada** [comment]
ahaha nice!

I referred in my comment to the setence [in this section](https://github.com/huggingface/transformers-bloom-inference/tree/03c0f9d7b59d661459fb24bcb820677cd584d086/bloom-inference-scripts#run) saying

> 1a. if you want to run the original bloom checkpoint, which once loaded will run at the same throughput as the previous solution, but the loading will take 10-20min:

<img width="1787" alt="Screenshot 2022-10-05 at 21 25 54" src="https://user-images.githubusercontent.com/49240599/194156579-0d46f801-fd21-4409-a6f9-734555d24101.png">


I think that there might be an off-the-shelf script to convert the pt checkpoints to the tp-pre-sharded checkpoints, but I am not sure, I thought that those checkpoints were stored on the cache once they are created

**Comment by mayank31398** [comment]
no, since this was meant for BLOOM and I don't have that much space, I never bothered to cache them.
Alternatively, if possible, you can use the [pre-sharded checkpoints](https://huggingface.co/microsoft/bloom-deepspeed-inference-fp16).

Otherwise, you can cache them yourself by passing `save_mp_checkpoint_path` to init_inference method.
However, I used this long ago and not sure if this still works

@younesbelkada

**Comment by younesbelkada** [comment]
Perfect! I will use the pre-sharded checkpoints from now ;) Thanks for your support @mayank31398

**Comment by mayank31398** [comment]
The first load is a little slow, but once Linux creates a cached buffer in system memory, you should be good to go.
First load for me is ~4 mins after a fresh system reboot and subsequent loads only take ~45 seconds.

**Comment by mayank31398** [comment]
closing this issue :)

**Comment by younesbelkada** [comment]
Perfect thanks! Can confirm the inference script works fine
Thanks for your help!
