### ISSUE TITLE
Running Error with microsoft/bloom-deepspeed-inference-fp16

### ISSUE THREAD

**Issue by yihaocs** [huggingface/transformers-bloom-inference#22]
Hi,

Thanks for the great repo! I have successfully run the bloom model on a 16X40GB machine via the following command:
```
deepspeed --num_gpus=16 bloom-inference-scripts/bloom-ds-inference.py --name bigscience/bloom --benchmark
```

When I change the model to microsoft/bloom-deepspeed-inference-fp16 via the following command:
```
deepspeed --num_gpus=16 bloom-inference-scripts/bloom-ds-inference.py --name microsoft/bloom-deepspeed-inference-fp16 --benchmark
```

It gives me the following error when Loading the checking points:

```
Traceback (most recent call last):
  File "bloom-inference-scripts/bloom-ds-inference.py", line 200, in <module>
    model = deepspeed.init_inference(
  File "/export/home/DeepSpeed/deepspeed/__init__.py", line 305, in init_inference
    engine = InferenceEngine(model,
  File "/export/home/DeepSpeed/deepspeed/inference/engine.py", line 149, in __init__
    self._apply_injection_policy(
  File "/export/home/DeepSpeed/deepspeed/inference/engine.py", line 367, in _apply_injection_policy
    replace_transformer_layer(
  File "/export/home/DeepSpeed/deepspeed/module_inject/replace_module.py", line 987, in replace_transformer_layer
    load_model_with_checkpoint(replaced_module,
  File "/export/home/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 229, in load_model_with_checkpoint
    load_module_recursive(r_module)
  File "/export/home/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 224, in load_module_recursive
    load_module_recursive(
  File "/export/home/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 224, in load_module_recursive
    load_module_recursive(
  File "/export/home/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 222, in load_module_recursive
    layer_policies[child.__class__](child, prefix + name + '.')
  File "/export/home/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 138, in load_transformer_layer
    load_parameters(child, prefix + n + '.')
  File "/export/home/DeepSpeed/deepspeed/module_inject/load_checkpoint.py", line 81, in load_parameters
    scale = scale.view(
AttributeError: 'NoneType' object has no attribute 'view'

Loading 8 checkpoint shards:  12%|██████████████████████████████████▏
```

I used the most recent transformers and DeepSpeed installed from the main branch:
```
>>> deepspeed.__version__
'0.7.4+cfead551'

>>> transformers.__version__
'4.22.0.dev0'
```

Really appreciate if you could provide some suggestions!

**Comment by mayank31398** [comment]
Hi @yihaocs thanks for trying out the repo.

microsoft/bloom-deepspeed-inference-fp16 have been resharded by microsoft for 8x A100 GPUs using tensor parallel. I don't think these will work for 16x tensor parallel out-of-the-box.
Do you really need the resharded weights?
Can you try passing save_mp_checkpoint_path in the following:
 https://github.com/microsoft/DeepSpeed/blob/b2a724e257e435b4b29faf913b689a7f16208c98/deepspeed/__init__.py#L225-L298
I haven't tried this personally but I think it should work.

Also, I didn't know servers existed with 16 GPUs 🤔 . Are all of these NVlink connected?

**Comment by yihaocs** [comment]
Hi Mayank,

Thank you very much for the quick reply and the suggestions! 

If I understand correctly, should I just create some empty directly and pass the path to the variable `save_mp_checkpoint_path` in https://github.com/huggingface/transformers-bloom-inference/blob/main/bloom-inference-scripts/bloom-ds-inference.py#L193-L200 . 

I just tried this but it does not work out. It still gives the same error. Is there anything I just missed? should I just delete the original hub model files and then pass the empty dir to `save_mp_checkpoint_path`?

FYI, GCP provides instances with 16 A100 GPUs: https://cloud.google.com/blog/products/compute/a2-vms-with-nvidia-a100-gpus-are-ga .

**Comment by mayank31398** [comment]
Yes, use --name = bigscience/bloom and save_mp_checkpoint_path = path where to dump the resharded weights.
But as I said, I never got to testing this unfortunately.

**Comment by yihaocs** [comment]
I see your points! I will have a try.  Really appreciate!

Best,
Yihao

**Comment by mayank31398** [comment]
@yihaocs did you get this to work?
If yes, can you tell me what you did.
I plan to add a resharding script here too that people can use themselves :)

**Comment by yihaocs** [comment]
Hi Mayank, 

I can get sharded files as you suggested, by passing a directory path to `save_mp_checkpoint_path`.  Which looks like:

```
config.json               tp_01_06.pt  tp_04_02.pt  tp_06_06.pt  tp_09_02.pt  tp_11_06.pt  tp_14_02.pt
ds_inference_config.json  tp_01_07.pt  tp_04_03.pt  tp_06_07.pt  tp_09_03.pt  tp_11_07.pt  tp_14_03.pt
non-tp.pt                 tp_02_00.pt  tp_04_04.pt  tp_07_00.pt  tp_09_04.pt  tp_12_00.pt  tp_14_04.pt
special_tokens_map.json   tp_02_01.pt  tp_04_05.pt  tp_07_01.pt  tp_09_05.pt  tp_12_01.pt  tp_14_05.pt
tokenizer.json            tp_02_02.pt  tp_04_06.pt  tp_07_02.pt  tp_09_06.pt  tp_12_02.pt  tp_14_06.pt
tokenizer_config.json     tp_02_03.pt  tp_04_07.pt  tp_07_03.pt  tp_09_07.pt  tp_12_03.pt  tp_14_07.pt
tp_00_00.pt               tp_02_04.pt  tp_05_00.pt  tp_07_04.pt  tp_10_00.pt  tp_12_04.pt  tp_15_00.pt
tp_00_01.pt               tp_02_05.pt  tp_05_01.pt  tp_07_05.pt  tp_10_01.pt  tp_12_05.pt  tp_15_01.pt
tp_00_02.pt               tp_02_06.pt  tp_05_02.pt  tp_07_06.pt  tp_10_02.pt  tp_12_06.pt  tp_15_02.pt
tp_00_03.pt               tp_02_07.pt  tp_05_03.pt  tp_07_07.pt  tp_10_03.pt  tp_12_07.pt  tp_15_03.pt
tp_00_04.pt               tp_03_00.pt  tp_05_04.pt  tp_08_00.pt  tp_10_04.pt  tp_13_00.pt  tp_15_04.pt
tp_00_05.pt               tp_03_01.pt  tp_05_05.pt  tp_08_01.pt  tp_10_05.pt  tp_13_01.pt  tp_15_05.pt
tp_00_06.pt               tp_03_02.pt  tp_05_06.pt  tp_08_02.pt  tp_10_06.pt  tp_13_02.pt  tp_15_06.pt
tp_00_07.pt               tp_03_03.pt  tp_05_07.pt  tp_08_03.pt  tp_10_07.pt  tp_13_03.pt  tp_15_07.pt
tp_01_00.pt               tp_03_04.pt  tp_06_00.pt  tp_08_04.pt  tp_11_00.pt  tp_13_04.pt
tp_01_01.pt               tp_03_05.pt  tp_06_01.pt  tp_08_05.pt  tp_11_01.pt  tp_13_05.pt
tp_01_02.pt               tp_03_06.pt  tp_06_02.pt  tp_08_06.pt  tp_11_02.pt  tp_13_06.pt
tp_01_03.pt               tp_03_07.pt  tp_06_03.pt  tp_08_07.pt  tp_11_03.pt  tp_13_07.pt
tp_01_04.pt               tp_04_00.pt  tp_06_04.pt  tp_09_00.pt  tp_11_04.pt  tp_14_00.pt
tp_01_05.pt               tp_04_01.pt  tp_06_05.pt  tp_09_01.pt  tp_11_05.pt  tp_14_01.pt
```
It will generate ds-inference_config.json and *.pt files based on the [linked code](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/module_inject/replace_module.py#L1017-L1071). 

However, after I copy related json files to the directory and pass the directory path to `--name`, 

```
deepspeed --num_gpus 16 bloom-inference-scripts/bloom-ds-inference.py --name /export/home/.cache/bloom-custom-mp-ckpt --benchmark
```

it fails and does not give any error I can track.

```
[2022-10-20 19:21:50,598] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.7.4+cfead551, git-hash=cfead551, git-branch=master
[2022-10-20 19:21:50,599] [INFO] [logging.py:68:log_dist] [Rank 0] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2022-10-20 19:21:50,738] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed-Inference config: 

{'layer_id': 0, 'hidden_size': 14336, 'intermediate_size': 57344, 'heads': 112, 
'num_hidden_layers': -1, 'fp16': True, 
'pre_layer_norm': True, 'local_rank': -1, 
'stochastic_mode': False, 'epsilon': 1e-05,
 'mp_size': 16, 'q_int8': False, 
'scale_attention': True, 
'triangular_masking': True,
'local_attention': False, 'window_size': 1, 
'rotary_dim': -1, 'rotate_half': 
False, 'rotate_every_two': True, 
'return_tuple': True, 
'mlp_after_attn': True, 
'mlp_act_func_type': <ActivationFuncType.GELU: 1>, 
'specialized_mode': False, 
'training_mp_size': 1, 'bigscience_bloom': True}

Loading 8 checkpoint shards:  88%|█████████████████████████████████████      | 7/8 [04:14<00:40, 40.05s/it][2022-10-20 19:26:27,205] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311357
[2022-10-20 19:26:29,010] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311358
[2022-10-20 19:26:30,841] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311359
[2022-10-20 19:26:32,790] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311360
[2022-10-20 19:26:34,740] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311361
[2022-10-20 19:26:36,651] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311362
[2022-10-20 19:26:38,522] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311363
[2022-10-20 19:26:38,522] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311364
[2022-10-20 19:26:40,553] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311365
[2022-10-20 19:26:42,465] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311366
Loading 8 checkpoint shards: 100%|██████████████████| 8/8 [04:47<00:00, 39.04s/it][2022-10-20 19:26:44,457] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311367
Loading 8 checkpoint shards: 100%|██████████████████| 8/8 [04:48<00:00, 39.12s/it][2022-10-20 19:26:46,486] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311368
[2022-10-20 19:26:48,610] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311369
[2022-10-20 19:26:50,774] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311370
[2022-10-20 19:26:52,937] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311371
[2022-10-20 19:26:55,099] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 1311372
[2022-10-20 19:26:57,381] [ERROR] [launch.py:292:sigkill_handler] ['/export/home/miniconda3/envs/hf/bin/python', '-u', 'bloom-inference-scripts/bloom-ds-inference.py', '--local_rank=15', '--name', '/export/home/.cache/bloom-custom-mp-ckpt', '--benchmark'] exits with return code = -9
```

Do you have any idea why this does not work? 

Thanks! 
Yihao

**Comment by yihaocs** [comment]
> 

I think it would be a great feature; but currently I am not sure what happens such that it does not work.

**Comment by yihaocs** [comment]
I just tested bloom-3b using the procedure I described for bloom. It works very well to shard the bloom-3b model. I can successfully shard the weights and loaded it again for inference.

**Comment by mayank31398** [comment]
I am not really sure and unfortunately I can't test this either.

**Comment by yihaocs** [comment]
I think it should work. The bug might come from the machine itself.

**Comment by yihaocs** [comment]
> @yihaocs did you get this to work? If yes, can you tell me what you did. I plan to add a resharding script here too that people can use themselves :)

Hi Mayank, 

Do you have any plan working on this recently? I think it would be a great feature for the repo.
