### ISSUE TITLE
Error running bloom-7b1 model with deepspeed

### ISSUE THREAD

**Issue by anoopkunchukuttan** [huggingface/transformers-bloom-inference#24]
Thanks for these scripts! I tried running the bloom-7b1 model 

```
deepspeed --num_gpus 8 bloom-inference-scripts/bloom-ds-inference.py --name 'bigscience/bloom-7b1'
```

I get the following error when loading the checkpoints: 

```
KeyError: 'h.19.input_layernorm.weight'
```

The following is the log

```
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                   | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
Traceback (most recent call last):
  File "bloom-inference-scripts/bloom-ds-inference.py", line 199, in <module>
  File "bloom-inference-scripts/bloom-ds-inference.py", line 199, in <module>
Traceback (most recent call last):
  File "bloom-inference-scripts/bloom-ds-inference.py", line 199, in <module>
    **kwargs,
      File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/__init__.py", line 326, in init_inference
**kwargs,
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/__init__.py", line 326, in init_inference
    **kwargs,
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/__init__.py", line 326, in init_inference
        base_dir)base_dir)

  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 158, in __init__
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 158, in __init__
    base_dir)
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 158, in __init__
        base_dir=base_dir)base_dir=base_dir)

  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 393, in _apply_injection_policy
      File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 393, in _apply_injection_policy
base_dir=base_dir)
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/inference/engine.py", line 393, in _apply_injection_policy
        enable_cuda_graph=self.enable_cuda_graph)enable_cuda_graph=self.enable_cuda_graph)
    
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/replace_module.py", line 962, in replace_transformer_layer
enable_cuda_graph=self.enable_cuda_graph)  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/replace_module.py", line 962, in replace_transformer_layer

  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/replace_module.py", line 962, in replace_transformer_layer
        quantizer,    quantizer,
quantizer,
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 229, in load_model_with_checkpoint

  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 229, in load_model_with_checkpoint
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 229, in load_model_with_checkpoint
        load_module_recursive(r_module)load_module_recursive(r_module)

  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 227, in load_module_recursive
      File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 227, in load_module_recursive
load_module_recursive(r_module)
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 227, in load_module_recursive
    level + 1)
      File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 227, in load_module_recursive
level + 1)
      File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 227, in load_module_recursive
level + 1)
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 227, in load_module_recursive
    level + 1)
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 222, in load_module_recursive
    level + 1)
      File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 222, in load_module_recursive
level + 1)
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 222, in load_module_recursive
    layer_policies[child.__class__](child, prefix + name + '.')
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 140, in load_transformer_layer
    layer_policies[child.__class__](child, prefix + name + '.')
      File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 140, in load_transformer_layer
layer_policies[child.__class__](child, prefix + name + '.')
  File "/home/deepspeed/deepspeed/lib/python3.7/site-packages/deepspeed/module_inject/load_checkpoint.py", line 140, in load_transformer_layer
    module.norm_w.data.copy_(sd[0][prefix + 'input_layernorm.' + 'weight'])
    KeyErrormodule.norm_w.data.copy_(sd[0][prefix + 'input_layernorm.' + 'weight']): 
    'h.19.input_layernorm.weight'module.norm_w.data.copy_(sd[0][prefix + 'input_layernorm.' + 'weight'])
KeyError
: 'h.19.input_layernorm.weight'
KeyError: 'h.19.input_layernorm.weight'
```

I am using the following versions:
transformers version: 4.23.1
deepspeed version: 0.7.4

Any help/suggestion would be very helpful!

**Comment by mayank31398** [comment]
Hi, I would duggest not to use DS-inference for a model like this.
I have tried upto ~30B model and I only saw performance improvement of upto ~4 msec/token which is not worth it.
Simplicity of code here, might benefit you and I would suggest to stick with HuggingFace code.

**Comment by mayank31398** [comment]
@anoopkunchukuttan you should be able to run this now. I have made significant changes to the code.

**Comment by anoopkunchukuttan** [comment]
Thanks @mayank31398, I will try this.
