### ISSUE TITLE
RuntimeError: Error building extension 'transformer_inference'

### ISSUE THREAD

**Issue by Mahyar-Ali** [huggingface/transformers-bloom-inference#48]
I'm trying to load the `bigscience/bloomz-3b` for some benchmarks using the `bloom-inference-scripts/bloom-ds-inference.py` script but upon execution it raises the error:

`FAILED: transformer_inference.so 
c++ pt_binding.o gelu.cuda.o relu.cuda.o layer_norm.cuda.o softmax.cuda.o dequantize.cuda.o apply_rotary_pos_emb.cuda.o transform.cuda.o -shared -lcurand -L/home/mahyar/anaconda3/envs/deepspeed-testing/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda-11.6/lib64 -lcudart -o transformer_inference.so
/usr/local/cuda-11.6/lib64/libcurand.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/mahyar/anaconda3/envs/deepspeed-testing/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/home/mahyar/anaconda3/envs/deepspeed-testing/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
`

`
RuntimeError: Error building extension 'transformer_inference'
[2023-02-02 03:27:36,042] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 11492
[2023-02-02 03:27:36,043] [ERROR] [launch.py:324:sigkill_handler] ['/home/mahyar/anaconda3/envs/deepspeed-testing/bin/python', '-u', 'bloom-inference-scripts/bloom-ds-inference.py', '--local_rank=0', '--name', 'bigscience/bloomz-3b'] exits with return code = 1
`

Env Details:
`pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3`

**Comment by mayank31398** [comment]
I guess you figured it out ;p
